apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hha63pptl-nodejs 
  janus-idp.io/tekton: hha63pptl-nodejs
  backstage.io/kubernetes-id: hha63pptl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hha63pptl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  