apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hha63pptl-nodejs
  janus-idp.io/tekton: hha63pptl-nodejs
  backstage.io/kubernetes-id: hha63pptl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hha63pptl-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
