apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hha63pptl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hha63pptl-nodejs 
  name: hha63pptl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hha63pptl-nodejs 
